### ISSUE TITLE
Add support for Octaves, Frequency, Amplitude

### ISSUE THREAD

**Issue by ReportCardsMC** [ReportCardsMC/SKNoise#2]
### Overview
This will add the rest of the parameters inside of the noise functions, allowing you to change the octaves, the frequency, the amplitude, and whether or not it's normalized.

### To-Do
- [x] Add Octaves Support
- [x] Add Frequency Support
- [x] Add Amplitude Support

**Comment by ReportCardsMC** [comment]
Finished in [0.1.3](https://github.com/ReportCardsMC/SKNoise/releases/tag/0.1.3)
